
<div class="&#10;            oucontent-saq&#10;           oucontent-saqtype-part"><div class="oucontent-saq-question"><p><span class="oucontent-inlinefigure" style="vertical-align:-10px;"><img src="http://learn3.open.ac.uk/pluginfile.php/808/mod_oucontent/oucontent/103/book_42.png" alt="Book" width="42" height="42"/></span>&#xA0;&#xA0;<b>Task B</b> (allow 30 minutes)</p><p>Read the <a href="olink.php?id=718&amp;targetdoc=Book+1+%E2%80%93+Exploring+health%2C+social+care+and+wellbeing" class="oucontent-olink"><b>Introduction</b></a><span class="oucontent-sidenote oucontent-linktip"><span class="oucontent-sidenote-inner"><span class="accesshide"> [</span>Tip: hold &#x2318; and click a link to open it in a new tab. (<a href="hidetip.php?tip=linktip">Hide tip</a>)</span><span class="accesshide">] </span></span><span style="font-size:0">&#xA0;</span><b> </b>and <b>Section A</b> (Basic human needs) in Book&#xA0;1.</p><p>You can read Book&#xA0;1 online or you can use the identical text in the hard copy book provided. If you choose to read it online, remember to navigate back to the learning guide when you finish.</p><p>Do you agree that needs described are essential for human survival? Can you think of any needs that are not covered?</p></div></div><div class="&#10;            oucontent-saq&#10;           oucontent-saqtype-part oucontent-part-last&#10;        "><div class="oucontent-saq-question"><p><span class="oucontent-inlinefigure" style="vertical-align:-10px;"><img src="http://learn3.open.ac.uk/pluginfile.php/808/mod_oucontent/oucontent/103/video_42.png" alt="Video" width="42" height="42"/></span>&#xA0;&#xA0;<span class="oucontent-inlinefigure" style="vertical-align:-10px;"><img src="http://learn3.open.ac.uk/pluginfile.php/808/mod_oucontent/oucontent/103/audio_42.png" alt="Audio" width="34" height="40"/></span>&#xA0;&#xA0;<b>Task C</b> (allow an hour and a half)</p><p>This video introduces Trevor and Dahlia, who you will encounter throughout Block&#xA0;1. Watch the video and notice what they consider to be Trevor’s basic needs.</p><div class="oucontent-media oucontent-media-mini"><div class="oucontent-default-filter "><span class="oumediafilter"><a href="http://learn3.open.ac.uk/pluginfile.php/808/mod_oucontent/oucontent/103/k217_2010j_b1_vid001_320x176.mp4?forcedownload=1" class="oumedialinknoscript">Download this video clip.</a><span id="filter_video_12874339251"></span></span><script type="text/javascript">
//<![CDATA[
document.getElementById("filter_video_12874339251").innerHTML = "<iframe tabindex=\"0\" title=\"Video player: Introducing \" width=\"320\" height=\"206\" frameborder=\"0\" scrolling=\"no\" style=\"overflow:hidden\" src=\"http:\/\/learn3.open.ac.uk\/local\/mediahack\/?title=Video+player%3A+Introducing+&amp;media_url=http%3A%2F%2Flearn3.open.ac.uk%2Fpluginfile.php%2F808%2Fmod_oucontent%2Foucontent%2F103%2Fk217_2010j_b1_vid001_320x176.mp4&amp;width=320&amp;height=206&amp;caption_url=k217_2010j_b1_vid001_320x176.srt\"><\/iframe>";

//]]>
</script>
</div><div class="oucontent-figure-text"><div class="oucontent-transcriptlink"><a href="view.php?id=718&amp;extra=transcript_id394406956061" title="Transcript (opens in new window)" onclick="return oucontentTranscript('view.php?id=718&amp;extra=transcript_id394406956061')">Transcript <img src="newwindow.png" alt="(opens in new window)"/></a></div><a name="transcript_id394406956061" id="back_transcript_id394406956061"></a>



<p class="test-note clearer">OUVLE video

<p class="hide source"><a href="http://learn3.open.ac.uk/mod/oucontent/view.php?id=718&section=2.1">K217-11B Activity 1.1: Basic requirements for...</a>

