languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- "application/assets/*"
- "application/config/*"
- "application/libraries/class.pdf2text.php"
- "application/libraries/POParser.php"
- "docs/*"
- "system/*"
