# see http://about.travis-ci.org/docs/user/languages/php/
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-source

script:
  - composer test

#End.
