# see https://docs.travis-ci.com/user/languages/php/
language: php

# blacklist
branches:
  except:
    - master
    - legacy
    - 1.x

git:
  depth: 8

php:
  - 5.6
  - 7.0
  #- hhvm

before_install:
  - nvm install v8
  #- npm install npm -g
  - npm --version
  - composer config --list

install:
  - composer generic-env
  - composer install
  - composer npm-install

script:
  - composer test
  - composer validate --no-interaction

notifications:
  email:
    recipients:
      - omp-techsupport@open.ac.uk
      #- iet-webmaster@open.ac.uk
    #on_success: always

#End.
