# see http://about.travis-ci.org/docs/user/languages/php/
language: php

# blacklist
branches:
  except:
    - master
    - legacy
    - 1.x

git:
  depth: 3

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-source

script:
  - composer test

notifications:
  email:
    recipients:
      - iet-webmaster@open.ac.uk
    #on_success: always

#End.

