# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
language: php

branches:
  # whitelist
  only:
    - 2.x

  # blacklist
  except:
    #- master
    #- legacy
    #- 1.x

# Just in case...!

git:
  depth: 2

install: true

script: echo Not running on this branch && exit 0

#End.
